#      █████╗  █████╗ ██████╗ ██╗ █████╗ ███████╗ █████╗ ██████╗ ███╗   ███╗██╗███╗  ██╗ ██████╗
#     ██╔══██╗██╔══██╗██╔══██╗██║██╔══██╗██╔════╝██╔══██╗██╔══██╗████╗ ████║██║████╗ ██║██╔════╝
#     ██║  ╚═╝███████║██║  ██║██║███████║█████╗  ███████║██████╔╝██╔████╔██║██║██╔██╗██║██║  ██╗
#     ██║  ██╗██╔══██║██║  ██║██║██╔══██║██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██║██║╚████║██║  ╚██╗
#     ╚█████╔╝██║  ██║██████╔╝██║██║  ██║██║     ██║  ██║██║  ██║██║ ╚═╝ ██║██║██║ ╚███║╚██████╔╝
#      ╚════╝ ╚═╝  ╚═╝╚═════╝ ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚══╝ ╚═════╝

# Valid Entity Types - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# Valid Block Materials - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

mob-drops:
  SHEEP:
    - "RED_WOOL%80"
    - "PINK_WOOL%20"
  COW:
    - "BROWN_WOOL%50"
    - "GOLD_BLOCK%50"

max-mobs-per-chunk: 12

MySQL:
  username: "root"
  password: "password"
  database: "minecraft"
  host: "localhost"
  port: 3306

# Do **NOT** change the numbers 1, 2, 3 etc. You may only change what is below them
GUI:
  1:
    displayname:
    lore:
      -
      -

  2:
    displayname:
    lore:
      -
      -

  3:
    displayname:
    lore:
      -
      -
  4:
    displayname:
    lore:
      -
      -
  5:
    displayname:
    lore:
      -
      -
